project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://api.crowdin.com

files:
- source: /src/locales/en/*.json
  translation: /src/locales/%locale_with_underscore%/%file_name%.%file_extension%
  update_option: update_as_unapproved
  skip_untranslated_strings: true
  export_only_approved: true
